### ISSUE TITLE
Evaluate all subpackages for package location and maintenance

### ISSUE THREAD

**Issue by 200sc** [oakmound/shiny#2]
There isn't a unifying characteristic about shiny's subpackages that holds them together as a unit, aside from `screen` and `driver`, and `example` which hopefully uses a lot of different elements from different packages.

We need to evaluate and determine if we care to maintain some of these subpackages or not, and if we do, if they should live under `shiny`. 

If something is checked off, we have decided what to do with it

- [x] `driver`: We will maintain this, and it will live in `shiny`
- [ ] `example`
- [x] `gesture`: We will maintain this, and it will live in `shiny`
- [ ] `iconvg`
- [ ] `imageutil`
- [ ] `materialdesign`: 
- [x] `screen`: We will maintain this, and it will live in `shiny`
- [ ] `text`
- [ ] `unit`
- [ ] `widget`

**Comment by 200sc** [comment]
Notes for right now:

`example` seems fine but we probably aren't going to put new examples in it, we'll probably invest on examples for `oak` instead, so claiming to maintain it is probably inaccurate. 

`materialdesign` is something like putting the cart before the horse. It's entirely dependent on `widget` being a good UI composition package to be remotely useful. Should it be a subpackage of `widget` (assuming we keep widget)?

`imageutil` has a single function that doesn't actually deal with images-- this almost certainly will just get removed, or moved to `oak/alg/intgeom`.

`widget` looks like it has real potential, and I was just thinking about making a library like this, so maintaining it seems like a good idea but I need to work with the API to figure out if I actually would use this or if I would want significant changes. 

`unit` Is practically a stub, and defines an interface that it knows how to make real answers for but chooses not to. We don't have a use-case for this because we define everything in terms of pixels, but if this was expanded to actually have converters, maybe it should stay?

`text` has an incomplete API, but could be useful if that API was finished

**Comment by joeblew99** [comment]
i see what you mean.

Regarding widget. I wonder if you plan to support different DPI and hence layout / reflow aspects for it. They started on layout using flex if i remember correctly. 

Also there are some excellent layout constraint solvers in macha that can be used with only a small amount of refactoring.
The good stuff here is really the layout and views architecture at the golang level, and i think this can be used with shiny to get a pretty amazing base.

https://github.com/gomatcha/matcha

https://github.com/gomatcha/matcha/tree/master/layout

It is explained here: https://github.com/gomatcha/matcha/blob/master/layout/layouter.go
And here: https://gomatcha.io/guide/concepts/

Just so its not confusing, Macha is designed to be used on IOS to built apps that use IOS native controls. What he has done is put all the logic and control at the golang level and then used Protobufs for talking to native to layout the IOS controls.

**Comment by 200sc** [comment]
I'll need to work with widget more (and won't have much time in the near future do so so due to work on getting a degree) before being able to answer confidently but I don't see a problem with supporting DPI / layout checks and transformations.
